server:
  port: 9000
  # 为什么要写 /api，这是做一个前置标识
  servlet:
    context-path: /api

spring:
  datasource:
    # 如果你的 MySQL 驱动 > 8.0 版本的，那么这里的驱动类要加上 cj
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml